

@baseUrl = https://congenial-space-goldfish-rjw9p5gggq9fwpp6-4000.app.github.dev

### Consulta

# @name createConsulta
POST {{baseUrl}}/consultas
Content-Type: application/json

{
  "data": "2025-09-05T10:00:00Z",
  "descricao": "Consulta de rotina",
  "medicoId": "840b4ba8-e82b-4d5a-a646-16c7c00c856a",
  "pacienteId": "3f4b40b4-2d76-4456-8bbf-575e5a51ebc7"
}


###

# @name getAllConsultas
GET {{baseUrl}}/consultas

###

# @name getConsultaById
GET {{baseUrl}}/consultas/c830bd72-59b5-4bae-89f0-16444fb40951

###

# @name updateConsulta
PUT {{baseUrl}}/consultas/c830bd72-59b5-4bae-89f0-16444fb40951
Content-Type: application/json

{
  "data": "2025-09-05T11:00:00Z",
  "descricao": "Retorno de consulta",
  "medicoId": "840b4ba8-e82b-4d5a-a646-16c7c00c856a",
  "pacienteId": "3f4b40b4-2d76-4456-8bbf-575e5a51ebc7"
}
###

# @name deleteConsulta
DELETE {{baseUrl}}/consultas/c830bd72-59b5-4bae-89f0-16444fb40951
