@baseUrl = https://congenial-space-goldfish-rjw9p5gggq9fwpp6-4000.app.github.dev


### Paciente

# @name createPaciente
POST {{baseUrl}}/paciente/pacientes
Content-Type: application/json

{
  "nome": "Maria Souzass",
  "email": "maraaiae.souza@example.acom",
  "dataNascimento": "1990-05-15"
}

###

# @name getAllPacientes
GET {{baseUrl}}/paciente/pacientes

### Buscar próximas consultas de um paciente
GET {{baseUrl}}/paciente/pacientes/3f4b40b4-2d76-4456-8bbf-575e5a51ebc7/proximas
Content-Type: application/json


###

# @name getPacienteById
GET {{baseUrl}}/paciente/pacientes/d4a0c30d-2041-48e9-83b1-d215b70ea066

###

# @name updatePaciente
PUT {{baseUrl}}/paciente/pacientes/d4a0c30d-2041-48e9-83b1-d215b70ea066
Content-Type: application/json

{
  "nome": "Maria Souza Lima",
  "email": "mariaaww.souza.lima@example.com",
  "dataNascimento": "1990-05-15"
}

###

# @name deletePaciente
DELETE {{baseUrl}}/paciente/pacientes/1c70e794-a00b-4df9-9641-c7b90ba360b1
Content-Type: application/json

